version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: telemed-postgres
    environment:
      POSTGRES_DB: telemed_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - telemed-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemed-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/telemed_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8080:8080"
    networks:
      - telemed-network
    restart: on-failure

volumes:
  postgres_data:

networks:
  telemed-network:
    driver: bridge
